#!/bin/bash

DIR=$(perl -e "use Cwd qw(abs_path); use File::Basename; print dirname(abs_path('$0'))")

echo "Mounting $DIR as /data"
docker run \
    --rm \
    -v "$DIR:/data" \
    -v "$DIR/.ssh:/tmp/.ssh" \
    --env ACCOUNT_ID=$ACCOUNT_ID \
    --env API_TOKEN=$API_TOKEN \
    --env PROJECT_ID=$PROJECT_ID \
    --entrypoint boot/run-in-docker.sh \
    smartcatcom/serge \
    "$@"
