# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  repository_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    env:
      ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
      API_TOKEN: ${{ secrets.API_TOKEN }}
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
    
      - name: Pull repository
        run: |
          docker pull smartcatcom/serge:latest
          ./run-in-docker serge pull --initialize stereotech.org.serge
